name: Stock Price ETL

on:
  schedule:
    - cron: '0 * * * *'  # This cron runs the job every hour
  workflow_dispatch:     # Allows manual triggers of the workflow

jobs:
  run-etl:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Update to v3 for Node.js 20 support

    - name: Set up Python
      uses: actions/setup-python@v4  # Update to v4 for Node.js 20 support
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests python-dotenv sqlite3

    - name: Run ETL Script
      run: |
        python data_fetch.py
